### ISSUE TITLE
dat website ui 

### ISSUE THREAD

**Issue by ghost** [CampbellCrowley/SpikeyBot-Discord#114]
just wanted to say that i have never seen an ugly website design like this before .spikeybot.com
was it soo hard to use bootstrap or something like that
realy

**Comment by CampbellCrowley** [comment]
Hey! Thanks you for your feedback on the website's appearance. I am not a UI designer, and thus especially appreciate feedback on how to improve the appearance. It would help me out greatly if you would be able to provide more specific details as to what issues you are having, and potentially provide suggestions for solutions, so that I am able to make educated improvements.

As this issue appears to be minimally constructive, I will be closing this issue for now. If you feel that you have more specific feedback to provide, feel free to re-open this issue.
